language: node_js
node_js: 
  - "8"

services:
  - docker

install:
  - docker build -t demo .
  - docker run -d -p 127.0.0.1:80:80 --name demo demo

before_script:
  - npm install

script:
  - docker ps | grep -q demo
  - npm test

